### ISSUE TITLE
argument Error while training

### ISSUE THREAD

**Issue by songhee-lee** [codertimo/KorQuAD-Question-Generation#1]
When I try to run training, I got this error.
>>> TypeError: __new__() got an unexpected keyword argument 'eval_batch_size'

It is okay without '--eval-batch-size'  like ' python -m scripts.run_fine_tune --train-batch-size 16 --epochs 5.

**Comment by TikaToka** [comment]
You can check pull-request. Fixed the error you issued :)

**Comment by codertimo** [comment]
#2 resolved this issue!
